spring:
  datasource:
    url: jdbc:postgresql://db_permission:5432/permission-db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10     # Adjust this based on your performance needs

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
          audience: dev-ppmfishyt4u8fel3.us.auth0.com

auth0:
  audience: https://snippets-api
  domain: dev-ppmfishyt4u8fel3.us.auth0.com

logging:
  level:
    root: DEBUG
