version: '3.8'

services:

  snippets_api:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - '8083:8083'
    environment:
      POSTGRES_HOST: snippets_db
      POSTGRES_DB: snippets_db
      POSTGRES_USER: snippets_user
      POSTGRES_PASSWORD: snippets_password
      POSTGRES_PORT: 5432
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: 'snippet-searcher'
      NEW_RELIC_AGENT_ENABLED: true
      NEW_RELIC_LOG_EXTENSION_ADD_MDC: true
      AUTH_SERVER_URI: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
      AUTH_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      spring.security.oauth2.resourceserver.jwt.issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
    depends_on:
      - snippets_db

  snippets_db:
    image: postgres:15
    environment:
      POSTGRES_DB: snippets_db
      POSTGRES_USER: snippets_user
      POSTGRES_PASSWORD: snippets_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  asset_service:
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "8080:8080"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: "api"
      NEW_RELIC_AGENT_ENABLED: false

  azuriteSnippets:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

  parseservice: # Cambié el nombre para evitar subrayados
    image: ghcr.io/teamverdeingsis/parse:latest
    ports:
      - "8081:8081"
    environment:
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: 'parseService2'
      NEW_RELIC_AGENT_ENABLED: true
      NEW_RELIC_LOG_EXTENSION_ADD_MDC: true
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
volumes:
  db_data:
    external: false
  blob:
    external: false
