version: '3.8'

services:
  snippets:
    container_name: "snippets-service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      # Referencing db_permission instead of db_snippets
      DB_HOST: db_permission
      DB_PORT: 5432
      DB_NAME: permission-db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - parse_service
      - permission_service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
