services:
  snippets_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    env_file:
      - .env
    depends_on:
      snippets_db:
        condition: service_healthy

  snippets_db:
    image: postgres
    platform: linux/amd64
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: snippets_db
    volumes:
      - snippets_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_APP_NAME: "asset-service"
      NEW_RELIC_AGENT_ENABLED: false


  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

volumes:
  snippets_db_data:
    external: false
  blob:
    external: false

