version: '3.8'

services:

  snippets_api:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - '8082:8081'
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: snippets_db
      POSTGRES_USER: snippets_user
      POSTGRES_PASSWORD: snippets_password
      POSTGRES_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-snippets
    environment:
      POSTGRES_DB: snippets_db
      POSTGRES_USER: snippets_user
      POSTGRES_PASSWORD: snippets_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "8080:8080"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: "api"
      NEW_RELIC_AGENT_ENABLED: false

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

volumes:
  db_data:
    external: false
  blob:
    external: false
