spring:
  application:
    name: snippets-service
  datasource:
    url: jdbc:postgresql://db-1:5432/snippets_db
    username: snippets_user
    password: snippets_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      platform: postgres

  security:
    user:
      name: root
      password: root

server:
  port: 8083