auth0:
  audience: https://snippet-service-api
spring:
  application:
    name: snippets-service
  datasource:
    url: jdbc:postgresql://localhost:5432/snippets_db
    username: snippets_user
    password: snippets_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-ppmfishyt4u8fel3.us.auth0.com/


server:
  port: 8083